//! Seoul legal-dong slugs used as the random component of generated
//! workspace/branch names.
//!
//! Romanisation follows the Revised Romanisation of Korean, with the
//! trailing `-dong`/`-ga` suffix dropped (`홍대입구동 → hongdae`,
//! `을지로1가 → euljiro`). Numbered administrative subdivisions such as
//! `상도1동 / 상도2동` collapse to a single entry (`sangdo`).
//!
//! Do not add duplicates. Entries must be lowercase, alphanumeric,
//! and ≤ 16 chars so they fit comfortably in git branch names.

pub(crate) const SEOUL_DONG: &[&str] = &[
    "ahyeon",
    "amsa",
    "anam",
    "apgujeong",
    "balsan",
    "bangbae",
    "banghak",
    "banghwa",
    "bangi",
    "banpo",
    "bogwang",
    "bomun",
    "bongcheon",
    "bonghyeon",
    "buam",
    "bukahyeon",
    "bukchon",
    "changjeon",
    "changseong",
    "cheongdam",
    "cheongnyangni",
    "cheongpa",
    "cheongun",
    "chungjeongno",
    "chungmuro",
    "daeheung",
    "daehak",
    "daehyeon",
    "daejo",
    "daelim",
    "daesin",
    "dangsan",
    "dapsimni",
    "deungchon",
    "dobong",
    "dogok",
    "dohwa",
    "doksan",
    "donam",
    "dongdaemun",
    "dongja",
    "dongjak",
    "dongseon",
    "dongsung",
    "dorim",
    "dunchon",
    "eungam",
    "eungbong",
    "euljiro",
    "gaebong",
    "gahoe",
    "gajwa",
    "galhyeon",
    "galwol",
    "gangil",
    "garak",
    "garosu",
    "gasan",
    "gayang",
    "geoje",
    "geumho",
    "gil",
    "gireum",
    "gocheok",
    "godeok",
    "gongdeok",
    "gongneung",
    "gunja",
    "guro",
    "gupabal",
    "gusan",
    "guui",
    "gwanak",
    "gwancheol",
    "gwangjang",
    "gwansu",
    "gwonnong",
    "gyeongun",
    "haebangchon",
    "haengdang",
    "hagye",
    "hannam",
    "hapjeong",
    "hawangsimni",
    "hengdang",
    "heukseok",
    "hongdae",
    "hongeun",
    "hongjae",
    "hugam",
    "hwanghak",
    "hwayang",
    "hyehwa",
    "hyeonseok",
    "hyoja",
    "ichon",
    "ikseon",
    "ilwon",
    "imun",
    "insa",
    "itaewon",
    "jagok",
    "jamsil",
    "jamwon",
    "janganpyeong",
    "jangchung",
    "jangji",
    "jangwi",
    "jayang",
    "jegi",
    "jeodong",
    "jeongneung",
    "jeonnong",
    "jongno",
    "junggok",
    "jungnang",
    "jungok",
    "macheon",
    "maegok",
    "majang",
    "mangwon",
    "mapo",
    "mia",
    "mok",
    "muk",
    "mullae",
    "munjeong",
    "munrae",
    "myeongdong",
    "myeongil",
    "myeongnyun",
    "myeonmok",
    "myo",
    "naegok",
    "namchang",
    "namdaemun",
    "namhyeon",
    "neung",
    "nogosan",
    "nokbeon",
    "nonhyeon",
    "noryangjin",
    "ogeum",
    "oksu",
    "ori",
    "oryu",
    "oryun",
    "palpan",
    "pil",
    "pungnap",
    "pyeongchang",
    "sadang",
    "sagan",
    "sajik",
    "samcheong",
    "samgak",
    "samjeon",
    "samseon",
    "samseong",
    "sangam",
    "sangbong",
    "sangdo",
    "sanggye",
    "sangil",
    "sangsu",
    "sangwangsimni",
    "seobinggo",
    "seocho",
    "seochon",
    "seodaemun",
    "seokchon",
    "seongbuk",
    "seongnae",
    "seongsan",
    "seongsu",
    "sicheong",
    "siheung",
    "sillim",
    "sincheon",
    "sinchon",
    "sindang",
    "sindorim",
    "sinjeong",
    "sinmun",
    "sinnae",
    "sinsa",
    "sinseol",
    "sinwol",
    "sogong",
    "sogyo",
    "songpa",
    "ssangmun",
    "suha",
    "susaek",
    "suseo",
    "suyu",
    "teheran",
    "ttukseom",
    "umyeon",
    "ui",
    "waryong",
    "wolgok",
    "wolgye",
    "yaksu",
    "yangcheon",
    "yangjae",
    "yangpyeong",
    "yeoksam",
    "yeokchon",
    "yeomchang",
    "yeomni",
    "yeongdeungpo",
    "yeonhui",
    "yeonji",
    "yeonnam",
    "yeouido",
    "yongang",
    "yongdu",
    "yongmun",
    "yongsan",
];

#[cfg(test)]
mod tests {
    use super::SEOUL_DONG;

    #[test]
    fn entries_are_lowercase_and_nontrivial() {
        for slug in SEOUL_DONG {
            assert!(!slug.is_empty(), "empty slug");
            assert!(
                slug.chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit()),
                "slug {slug:?} contains non-lowercase ascii"
            );
            assert!(slug.len() <= 16, "slug {slug:?} is too long");
        }
    }

    #[test]
    fn no_duplicates() {
        let mut sorted: Vec<&&str> = SEOUL_DONG.iter().collect();
        sorted.sort();
        for w in sorted.windows(2) {
            assert_ne!(w[0], w[1], "duplicate slug: {}", w[0]);
        }
    }

    #[test]
    fn has_at_least_150_entries() {
        assert!(
            SEOUL_DONG.len() >= 150,
            "expected ≥150 entries, got {}",
            SEOUL_DONG.len()
        );
    }
}
